### ISSUE TITLE
repo: complete Community Standards checklist

### ISSUE THREAD

**Issue by David-Pena** [David-Pena/slash-fix#3]
Must-Have sections:

- [X] Description
- [X] README https://github.com/David-Pena/slash-fix/commit/d86a9954778d97b45a10223430c8e4f517737e07
- [ ] Code of Conduct
- [X] Contributing https://github.com/David-Pena/slash-fix/commit/d86a9954778d97b45a10223430c8e4f517737e07
- [X] License https://github.com/David-Pena/slash-fix/commit/4da288efc57b42a6ecff1b88457d1102271e5f7f
- [ ] Security Policy
- [ ] Issue templates
- [ ] Pull request template

For more information [Click here 🔗](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/about-community-profiles-for-public-repositories#using-the-community-profile-checklist-as-a-community-member-or-collaborator)
